# Project: MyDos
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o function.o MYDOS.o
LINKOBJ  = main.o function.o MYDOS.o
LIBS     = -L"D:/software/mingw/install/MinGW/lib" -L"D:/software/mingw/install/MinGW/x86_64-w64-mingw32/lib" -static-libstdc++ -static-libgcc
INCS     = -I"D:/software/mingw/install/MinGW/include" -I"D:/software/mingw/install/MinGW/x86_64-w64-mingw32/include" -I"D:/software/mingw/install/MinGW/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/software/mingw/install/MinGW/include" -I"D:/software/mingw/install/MinGW/x86_64-w64-mingw32/include" -I"D:/software/mingw/install/MinGW/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
BIN      = MyDos.exe
CXXFLAGS = $(CXXINCS) -std=c++17
CFLAGS   = $(INCS) -std=c++17
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

function.o: function.cpp
	$(CPP) -c function.cpp -o function.o $(CXXFLAGS)

MYDOS.o: MYDOS.cpp
	$(CPP) -c MYDOS.cpp -o MYDOS.o $(CXXFLAGS)
